rootUrl: http://localhost:3000
gridUrl: http://127.0.0.1:4444/wd/hub
windowSize: 1400x900
compositeImage: true
sessionsPerBrowser: 3
retry: 1

browsers:
  chrome-latest:
    desiredCapabilities:
      version: "37.0"
      browserName: chrome
      platform: MAC

system:
  exclude:
    - node_modules/**
  plugins:
    gemini-babel: true
