rootUrl: http://localhost:3000
gridUrl: http://127.0.0.1:4444/wd/hub
windowSize: 1400x900
compositeImage: true
sessionsPerBrowser: 5
tolerance: 3
sessionRequestTimeout: 2000

browsers:
  chrome-latest:
    desiredCapabilities:
      version: "58.0"
      browserName: chrome

system:
  exclude:
    - node_modules/**
  plugins:
    gemini-babel: true
