rootUrl: http://localhost:3000
gridUrl: http://127.0.0.1:4444/wd/hub
windowSize: 1400x900
sessionsPerBrowser: 2

browsers:
  chrome-latest:
    desiredCapabilities:
      version: "37.0"
      browserName: chrome
      platform: MAC

system:
  debug: true
  plugins:
    gemini-babel: true
